outfile: evaluation_results.txt
min_digit: 5
max_digit: 100
digits: [5, 10, 20, 50, 100]
samples: 1000
metrics:
  - step_accuracy
  - full_sample_accuracy
  - full_sample_off_by_one

models:
  # [DisplayName, PathToOutputFolder, Checkpoint]
  - ["Lens Transformer", "outputs/model_full", "best"]