[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
include = ["src/**/*.py"]

[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.venv
  | venv
)/
'''

[project]
name = "DL25"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    # Dev Utils
    "black==25.9.0",
    "pre-commit==4.3.0",
    "hydra-core==1.3.2",
    "torchinfo==1.8.0",
    # Core
  # "torch",        # Manually install to match Accelerator version
  # "torchvision",  # Manually install to match Accelerator version
  # "lightning",  # Manually install to match Accelerator version
    "einops==0.8.1",
    "x-transformers==2.9.2",
]
authors = [
  {name = "Cyril Moser"},
  {name = "Gent Serifi"},
  {name = "Nicola Studer"},
  {name = "Aaron Zeller"},
]

description = "Transformers as Algorithmic Reasoners: A 2D Blackboard Approach"
readme = "README.md"