defaults:
  - _self_
  - runtime: default
  - logging: default
  - optim: adam
  - dataset: multidataset
  - model: rope_encoding
  - head: global_action_distribution

name: multi
val_split: 0.1
batch_size: 64
n_epochs: 20
resume: false
resume_ckpt: null

hydra:
  run:
    dir: outputs/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}