defaults:
  - config
  - blocks@model.lens: lens_3_3_3_3_1
  - override model: lens_transformer
  - _self_

name: lens_transformer_3_3_3_3_1_softmask_proj_grad
n_epochs: 1000
proj_grad: false
mix_grad: true
val_min_digits: 1
val_max_digits: 18

model:
  mask_type: soft

head:
  n_registers: 0

dataset:
  n_samples: 10000
  max_digits: 3

logging:
  save_every_n_epochs: 3
  val_every_n_epochs: 3

runtime:
  n_workers: 4